export interface GameInfo {
  slug: string
  name: string
  category: string
  emoji: string
  description: string
  multiplayer: boolean
  type: 'internal' | 'iframe' | 'native'
  badge?: string
  iframeSrc?: string
  componentName: string
}

export const GAMES_REGISTRY: GameInfo[] = [
  {
    slug: 'cricket',
    name: 'Hand Cricket',
    category: 'Social',
    emoji: '🏏',
    description: 'Classic Indian hand cricket! Rebuilt with configurable wickets, overs, toss system, and interactive bowling vs AI.',
    multiplayer: true,
    type: 'internal',
    badge: 'Live',
    componentName: 'cricket',
  },
  {
    slug: 'scribble',
    name: 'Scribble',
    category: 'Social',
    emoji: '🎨',
    description: 'Draw and guess with friends in real time. Create or join a room.',
    multiplayer: true,
    type: 'internal',
    badge: 'Hot',
    componentName: 'scribble',
  },
  {
    slug: 'dumb-charades',
    name: 'Dumb Charades',
    category: 'Social',
    emoji: '🎭',
    description: 'Act out movies and shows with only text hints. Your team guesses!',
    multiplayer: true,
    type: 'internal',
    badge: 'Parties',
    componentName: 'charades',
  },
  {
    slug: 'whos-spy',
    name: "Who's Spy",
    category: 'Social',
    emoji: '🕵️',
    description: 'Everyone gets the same word — except the spy. Discuss, deduce, and vote!',
    multiplayer: true,
    type: 'internal',
    badge: 'Social',
    componentName: 'spy',
  },
  {
    slug: 'tic-tac-toe',
    name: 'Tic-Tac-Toe',
    category: 'Dual Player',
    emoji: '⭕',
    description: 'Classic 3×3 noughts-and-crosses with an XP twist. Ranked and unranked modes.',
    multiplayer: true,
    type: 'internal',
    badge: 'Ranked',
    componentName: 'ttt',
  },
  {
    slug: 'word-wizard',
    name: 'Word Wizard',
    category: 'Puzzle',
    emoji: '📝',
    description: 'Spot hidden words in a letter grid before time runs out.',
    multiplayer: false,
    type: 'internal',
    badge: 'Smart',
    componentName: 'wordwizard',
  },
  {
    slug: 'rps',
    name: 'Rock Paper Scissors',
    category: 'Dual Player',
    emoji: '✊',
    description: 'The classic showdown. Best of 3. No luck — just reads.',
    multiplayer: true,
    type: 'internal',
    badge: 'Quick',
    componentName: 'rps',
  },
  {
    slug: 'number-guessing',
    name: 'Number Guessing',
    category: 'Dual Player',
    emoji: '🔢',
    description: 'Guess the secret number between 1–100. Hot and cold feedback.',
    multiplayer: true,
    type: 'internal',
    badge: 'Random',
    componentName: 'numguess',
  },
  {
    slug: '2048',
    name: '2048',
    category: 'Puzzle',
    emoji: '🔢',
    description: 'Slide tiles and merge them to reach 2048.',
    multiplayer: false,
    type: 'native',
    badge: 'Puzzle',
    componentName: '2048',
  },
  {
    slug: 'fighter',
    name: 'Fighter Jet',
    category: 'Arcade',
    emoji: '✈️',
    description: 'Dodge enemies and shoot your way to the top of the score chart.',
    multiplayer: false,
    type: 'native',
    badge: 'Arcade',
    componentName: 'fighter',
  },
  {
    slug: 'ludo',
    name: 'Ludo',
    category: 'Strategy',
    emoji: '🎲',
    description: 'Classic Ludo board game. Race your pieces home.',
    multiplayer: false,
    type: 'iframe',
    badge: 'Board',
    iframeSrc: '/legacy-v1/Ludogame/index.html',
    componentName: 'iframe',
  },
  {
    slug: 'memory',
    name: 'Memory Match',
    category: 'Dual Player',
    emoji: '🃏',
    description: 'Flip cards, find pairs. A timeless memory challenge.',
    multiplayer: true,
    type: 'internal',
    badge: 'Memory',
    componentName: 'memory',
  },
  {
    slug: 'arrow-puzzle',
    name: 'Arrow Puzzle',
    category: 'Puzzle',
    emoji: '➡️',
    description: 'Clear the board by removing arrows with unobstructed paths in the direction they point.',
    multiplayer: false,
    type: 'internal',
    badge: 'New',
    componentName: 'arrowpuzzle',
  },
  {
    slug: 'color-sort',
    name: 'Color Sort',
    category: 'Puzzle',
    emoji: '🧪',
    description: 'Sort all colored liquids into separate jars.',
    multiplayer: false,
    type: 'internal',
    badge: 'New',
    componentName: 'colorsort',
  },
  {
    slug: 'unblock-traffic',
    name: 'Unblock Traffic',
    category: 'Puzzle',
    emoji: '🚗',
    description: 'Move vehicles to clear a path for the target vehicle to escape.',
    multiplayer: false,
    type: 'internal',
    badge: 'New',
    componentName: 'unblocktraffic',
  },
  {
    slug: 'water-connect',
    name: 'Water Connect',
    category: 'Puzzle',
    emoji: '💧',
    description: 'Connect matching color nodes to cover the entire grid. Paths cannot cross!',
    multiplayer: false,
    type: 'internal',
    badge: 'New',
    componentName: 'waterconnect',
  },
  {
    slug: 'dots-boxes',
    name: 'Dots & Boxes',
    category: 'Dual Player',
    emoji: '🕹️',
    description: 'Connect dots with lines to claim boxes. Claim more boxes than your opponent to win!',
    multiplayer: true,
    type: 'internal',
    badge: 'New',
    componentName: 'dotsboxes',
  },
  {
    slug: 'block-blast',
    name: 'Block Blast',
    category: 'Puzzle',
    emoji: '⏹️',
    description: 'Place block shapes on the 8x8 grid. Clear rows and columns to score and build combos.',
    multiplayer: false,
    type: 'internal',
    badge: 'New',
    componentName: 'blockblast',
  },
  {
    slug: 'neon-tetris',
    name: 'Neon Tetris',
    category: 'Arcade',
    emoji: '🕹️',
    description: 'Glowing retro neon Tetris. Rotate, slide, and drop tetrominoes with SRS wall kicks, daily challenges, and combo chains.',
    multiplayer: false,
    type: 'internal',
    badge: 'New',
    componentName: 'neontetris',
  },
  {
    slug: 'ai-infinite-candy-crush',
    name: 'Candy Blast Infinity',
    category: 'Match-3',
    emoji: '🍬',
    description: 'Procedurally generated match-3 puzzle game. Match delicious candies and juicy fruits, trigger cascading combos, and clear challenging objectives!',
    multiplayer: false,
    type: 'internal',
    badge: 'New',
    componentName: 'candycrush',
  },
  {
    slug: 'hangman',
    name: 'Hangman',
    category: 'Social',
    emoji: '🪓',
    description: 'Guess the hidden word letter by letter. Play solo or challenge opponents online!',
    multiplayer: true,
    type: 'internal',
    badge: 'New',
    componentName: 'hangman',
  },
]

export function getGameBySlug(slug: string): GameInfo | undefined {
  return GAMES_REGISTRY.find((g) => g.slug === slug)
}
